### ISSUE TITLE
Massive code review

### ISSUE THREAD

**Issue by Mehonoshin** [mkdevprogects/patients#18]
1) https://github.com/mkdevprogects/patients/tree/master/app/controllers/patient - давай удалим эту папочку, раз уж не кастомизуем девайс
2) https://github.com/mkdevprogects/patients/blob/master/app/controllers/clinics_controller.rb#L14
тут имеет смысл сделать `@clinic ||= Clinic.find(params[:id])` чтобы каждый раз не загружать клинику
3) https://github.com/mkdevprogects/patients/blob/master/app/controllers/illnesses_controller.rb#L2 - почему метод index пустой? Если не используется - надо удалить его.
4) https://github.com/mkdevprogects/patients/blob/master/app/decorators/specializations/doctor_decorator.rb - если декоратор пустой, то возможно стоит его удалить и использовать базовый DoctorDecorator
5) https://github.com/mkdevprogects/patients/blob/master/app/decorators/doctor_decorator.rb#L12 - почему показываем только первый грейд?
6) https://github.com/mkdevprogects/patients/blob/master/app/decorators/has_human_date.rb#L2 - переименовать чтобы было понятно, что метод не просто возвращает абы какую дату, а понятную человеку
7) https://github.com/mkdevprogects/patients/blob/master/app/decorators/visit_decorator.rb#L7 - заюзать модуль has_human_date вместо этого метода, чтобы было единообразие не надо именовать методы, которые делают одно и тоже - по разному
8) https://github.com/mkdevprogects/patients/blob/master/app/models/clinic.rb#L11 переписать эту конструкцию с помощью active_record и joins чтобы за один запрос из БД получить список названий специализаций(если не знаешь как - спрашивай)
9) https://github.com/mkdevprogects/patients/blob/master/app/models/disease.rb#L14 - аналогично, надо передать чтобы из БД доставать сразу список
10) https://github.com/mkdevprogects/patients/blob/master/app/models/patient.rb#L2 - вынести код связанный с Devise - в отдельный модуль, тк в других приложениях, модели для авторизации будут другими./
11) https://github.com/mkdevprogects/patients/blob/master/app/models/prescription.rb#L3 - добавить валидации доктора и болезни, так как без них рецепт не имеет смысла
12) https://github.com/mkdevprogects/patients/blob/master/app/models/specialization.rb#L1 - добавить валидации на обязательные поля специализации, например title
13) https://github.com/mkdevprogects/patients/blob/master/app/models/symptom.rb#L12 - не имеет смысла, так как симптом - это справочник. Зачем нам дата создания симптома в болезни.
Конструкция `illness_symptoms.find(self.id).created_at` отдаст дату последнего назначения этого симптома какой-нибудь болезни. Более того, она ее не отдаст, так как ты ищешь симптом конкретной болезно, по id симптома из справочника.
Т.е. `illness_symptoms.find_by(symptom_idself.id).created_at` еще имело бы смысл, но я не понимаю всеравно для чего.
14) https://github.com/mkdevprogects/patients/blob/master/app/views/clinics/index.html.erb#L2 - если делаем приложение с упором на поддержку разных языков, то имеет смысл вынести русские тексты в I18n
15) https://github.com/mkdevprogects/patients/blob/master/app/views/clinics/show.html.erb#L4 - что за странные пробелы?
16) https://github.com/mkdevprogects/patients/blob/master/app/views/diseases/index.html.erb#L4 - вот это имеет смысл вынести в partial, т.к. повторяется в разных вьюхах
17) https://github.com/mkdevprogects/patients/blob/master/app/views/illnesses/_symptoms.html.erb#L14 - `style=width=15%` вынеси в css и заюзай css-класс
18) https://github.com/mkdevprogects/patients/blob/master/app/views/illnesses/index.html.erb#L15 - зачем illness.id можно просто передать illness
19) https://github.com/mkdevprogects/patients/blob/master/app/views/illnesses/show.html.erb#L14 - `"#{@illness.doctor.surname} #{@illness.doctor.name}"` лучше вынести в декоратор, так как это логика отображения
20) https://github.com/mkdevprogects/patients/blob/master/config/routes.rb#L14 - удаляй автосгенерированные комменты, не несущие особого смысла для приложения
21) https://github.com/mkdevprogects/patients/blob/master/config/routes.rb#L14 - не нужно тут подставлять id, просто сделай
```
FactoryGirl.define do
  factory :disease_symptom do
    disease
    symptom
  end
end
```
и в аналогичных фабриках также
22) https://github.com/mkdevprogects/patients/blob/master/spec/controllers/clinics_controller_spec.rb#L8 дописать тесты, которые проверяют наличие данных о клиниках на странице(если не разберешься - спроси как) Аналогично для других тестов контроллеров
23) https://github.com/mkdevprogects/patients/blob/master/spec/rails_helper.rb#L9 - удаляй ненужные комменты
24) https://github.com/mkdevprogects/patients/blob/master/Gemfile - и тут комменты не нужны

**Comment by ToshiDono** [comment]
@Mehonoshin 

> https://github.com/mkdevprogects/patients/blob/master/app/decorators/doctor_decorator.rb#L12 - почему показываем только первый грейд?

Первый грейд на странице со списком всех врачей показываем, чтобы не засорять страницу лишней информацией, на странице врача выводим все грейды.

**Comment by ToshiDono** [comment]
@Mehonoshin 

> https://github.com/mkdevprogects/patients/blob/master/app/models/patient.rb#L2 - вынести код связанный с Devise - в отдельный модуль, тк в других приложениях, модели для авторизации будут другими./

Вынес девайз в отдельный модуль, подключил в модель пациента, получил ошибку undefined method `devise' for CustomDevise:Module
Что странно, т.к. в Patient я не подключал девайз напрямую, только использовал его методы.

**Comment by ToshiDono** [comment]
@Mehonoshin 

> https://github.com/mkdevprogects/patients/blob/master/app/models/symptom.rb#L12 - не имеет смысла, так как симптом - это справочник. Зачем нам дата создания симптома в болезни.
Конструкция illness_symptoms.find(self.id).created_at отдаст дату последнего назначения этого симптома какой-нибудь болезни. Более того, она ее не отдаст, так как ты ищешь симптом конкретной болезно, по id симптома из справочника.
Т.е. illness_symptoms.find_by(symptom_idself.id).created_at еще имело бы смысл, но я не понимаю всеравно для чего.

Задача - к каждому симптому текущей болезни вывести дату его регистрации.

**Comment by Mehonoshin** [comment]
> Задача - к каждому симптому текущей болезни вывести дату его регистрации(т.е. когда он появился у этого пациента)

тогда лучше сделать, так как название created_at никогда не юзай для своих методов в моделях. Оно зарезервировано для ActiveRecord

```
  def first_occurence_date
    illness_symptoms.find_by(symptom_id: self.id).created_at
  end
```

**Comment by Mehonoshin** [comment]
> Вынес девайз в отдельный модуль, подключил в модель пациента, получил ошибку undefined method `devise' for CustomDevise:Module
Что странно, т.к. в Patient я не подключал девайз напрямую, только использовал его методы.

Ок, тогда пока забей, сделаем это в рамках задачи по вытаскиванию моделей в gem
